-- =====================================================================
-- AutoPro Taller Automotriz — schema.sql
-- PostgreSQL 16 · Normalizado a 3FN
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE SEQUENCE IF NOT EXISTS seq_folio_orden START 1;
CREATE SEQUENCE IF NOT EXISTS seq_folio_pago  START 1;

-- 1. SEGURIDAD: roles y usuarios
CREATE TABLE IF NOT EXISTS roles (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR(30)  NOT NULL UNIQUE,
  descripcion VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS usuarios (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rol_id        INTEGER      NOT NULL REFERENCES roles(id),
  nombre        VARCHAR(100) NOT NULL,
  email         VARCHAR(120) NOT NULL
                CHECK (email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
  password_hash VARCHAR(255) NOT NULL,
  activo        BOOLEAN      NOT NULL DEFAULT TRUE,
  ultimo_login  TIMESTAMPTZ,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_usuarios_email ON usuarios (LOWER(email));
CREATE INDEX IF NOT EXISTS ix_usuarios_rol ON usuarios (rol_id);

-- 2. CRM: clientes y vehículos
CREATE TABLE IF NOT EXISTS clientes (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre     VARCHAR(120) NOT NULL,
  telefono   VARCHAR(20)  NOT NULL,
  email      VARCHAR(120)
             CHECK (email IS NULL OR email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
  direccion  VARCHAR(200),
  rfc        VARCHAR(13)
             CHECK (rfc IS NULL OR char_length(rfc) BETWEEN 12 AND 13),
  notas      TEXT,
  activo     BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_clientes_nombre_trgm   ON clientes USING GIN (nombre gin_trgm_ops);
CREATE INDEX IF NOT EXISTS ix_clientes_telefono      ON clientes (telefono);

CREATE TABLE IF NOT EXISTS vehiculos (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id  INTEGER      NOT NULL REFERENCES clientes(id),
  placas      VARCHAR(10)  NOT NULL UNIQUE,
  vin         VARCHAR(17)  UNIQUE
              CHECK (vin IS NULL OR char_length(vin) = 17),
  marca       VARCHAR(50)  NOT NULL,
  modelo      VARCHAR(60)  NOT NULL,
  anio        SMALLINT     NOT NULL CHECK (anio BETWEEN 1950 AND 2100),
  color       VARCHAR(30),
  kilometraje INTEGER      NOT NULL DEFAULT 0 CHECK (kilometraje >= 0),
  motor       VARCHAR(60),
  cilindros   SMALLINT     CHECK (cilindros IS NULL OR cilindros BETWEEN 1 AND 16),
  transmision VARCHAR(30),
  combustible VARCHAR(30),
  activo      BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_vehiculos_cliente ON vehiculos (cliente_id);
CREATE INDEX IF NOT EXISTS ix_vehiculos_marca_modelo ON vehiculos (marca, modelo);

-- 3. EQUIPO: mecánicos
CREATE TABLE IF NOT EXISTS mecanicos (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id   INTEGER UNIQUE REFERENCES usuarios(id) ON DELETE SET NULL,
  nombre       VARCHAR(100) NOT NULL,
  especialidad VARCHAR(60)  NOT NULL,
  telefono     VARCHAR(20),
  tarifa_hora  NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (tarifa_hora >= 0),
  estatus      VARCHAR(15)  NOT NULL DEFAULT 'disponible'
               CHECK (estatus IN ('disponible', 'ocupado', 'descanso')),
  activo       BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_mecanicos_estatus ON mecanicos (estatus) WHERE activo;

-- 4. CATÁLOGOS: categorías, servicios, refacciones
CREATE TABLE IF NOT EXISTS categorias (
  id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(60) NOT NULL,
  tipo   VARCHAR(10) NOT NULL CHECK (tipo IN ('servicio', 'refaccion')),
  activo BOOLEAN     NOT NULL DEFAULT TRUE,
  UNIQUE (nombre, tipo)
);

CREATE TABLE IF NOT EXISTS servicios (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_id   INTEGER       NOT NULL REFERENCES categorias(id),
  codigo         VARCHAR(20)   NOT NULL UNIQUE,
  nombre         VARCHAR(120)  NOT NULL,
  descripcion    TEXT,
  horas_estandar NUMERIC(5,2)  NOT NULL CHECK (horas_estandar > 0),
  precio_base    NUMERIC(12,2) NOT NULL CHECK (precio_base >= 0),
  activo         BOOLEAN       NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_servicios_categoria ON servicios (categoria_id);
CREATE INDEX IF NOT EXISTS ix_servicios_nombre_trgm ON servicios USING GIN (nombre gin_trgm_ops);

CREATE TABLE IF NOT EXISTS refacciones (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_id   INTEGER       NOT NULL REFERENCES categorias(id),
  sku            VARCHAR(30)   NOT NULL UNIQUE,
  nombre         VARCHAR(120)  NOT NULL,
  marca          VARCHAR(60),
  costo          NUMERIC(12,2) NOT NULL CHECK (costo >= 0),
  precio_publico NUMERIC(12,2) NOT NULL CHECK (precio_publico >= 0),
  stock          INTEGER       NOT NULL DEFAULT 0 CHECK (stock >= 0),
  stock_minimo   INTEGER       NOT NULL DEFAULT 5 CHECK (stock_minimo >= 0),
  activo         BOOLEAN       NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_refacciones_categoria ON refacciones (categoria_id);
CREATE INDEX IF NOT EXISTS ix_refacciones_nombre_trgm ON refacciones USING GIN (nombre gin_trgm_ops);
CREATE INDEX IF NOT EXISTS ix_refacciones_stock_bajo ON refacciones (stock) WHERE activo;

-- 5. NÚCLEO: órdenes de trabajo y su detalle
CREATE TABLE IF NOT EXISTS ordenes_trabajo (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio               VARCHAR(20) NOT NULL UNIQUE
                      DEFAULT ('OT-' || TO_CHAR(NOW(), 'YYYY') || '-' ||
                               LPAD(NEXTVAL('seq_folio_orden')::TEXT, 5, '0')),
  vehiculo_id         INTEGER     NOT NULL REFERENCES vehiculos(id),
  mecanico_id         INTEGER     REFERENCES mecanicos(id),
  creado_por          INTEGER     NOT NULL REFERENCES usuarios(id),
  estado              VARCHAR(15) NOT NULL DEFAULT 'programada'
                      CHECK (estado IN ('programada', 'en_revision', 'en_reparacion',
                                        'completada', 'entregada', 'cancelada')),
  bahia               VARCHAR(10),
  km_entrada          INTEGER     NOT NULL DEFAULT 0 CHECK (km_entrada >= 0),
  motivo              TEXT        NOT NULL,
  diagnostico         TEXT,
  motivo_cancelacion  TEXT,
  fecha_ingreso       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  fecha_estimada      DATE,
  fecha_cierre        TIMESTAMPTZ,
  iva_porcentaje      NUMERIC(5,2)  NOT NULL DEFAULT 16.00 CHECK (iva_porcentaje >= 0),
  subtotal_mano_obra  NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (subtotal_mano_obra >= 0),
  subtotal_refacciones NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (subtotal_refacciones >= 0),
  iva_monto           NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (iva_monto >= 0),
  total               NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (total >= 0),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (fecha_cierre IS NULL OR fecha_cierre >= fecha_ingreso),
  CHECK (estado <> 'cancelada' OR motivo_cancelacion IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS ix_ordenes_vehiculo ON ordenes_trabajo (vehiculo_id);
CREATE INDEX IF NOT EXISTS ix_ordenes_mecanico ON ordenes_trabajo (mecanico_id);
CREATE INDEX IF NOT EXISTS ix_ordenes_estado   ON ordenes_trabajo (estado);
CREATE INDEX IF NOT EXISTS ix_ordenes_fecha    ON ordenes_trabajo (fecha_ingreso);

CREATE TABLE IF NOT EXISTS orden_servicios (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id        INTEGER       NOT NULL REFERENCES ordenes_trabajo(id) ON DELETE CASCADE,
  servicio_id     INTEGER       NOT NULL REFERENCES servicios(id),
  cantidad        INTEGER       NOT NULL DEFAULT 1 CHECK (cantidad > 0),
  horas           NUMERIC(5,2)  NOT NULL CHECK (horas > 0),
  precio_unitario NUMERIC(12,2) NOT NULL CHECK (precio_unitario >= 0),
  importe         NUMERIC(12,2) GENERATED ALWAYS AS (cantidad * precio_unitario) STORED,
  UNIQUE (orden_id, servicio_id)
);
CREATE INDEX IF NOT EXISTS ix_orden_servicios_servicio ON orden_servicios (servicio_id);

CREATE TABLE IF NOT EXISTS orden_refacciones (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id        INTEGER       NOT NULL REFERENCES ordenes_trabajo(id) ON DELETE CASCADE,
  refaccion_id    INTEGER       NOT NULL REFERENCES refacciones(id),
  cantidad        INTEGER       NOT NULL CHECK (cantidad > 0),
  costo_unitario  NUMERIC(12,2) NOT NULL CHECK (costo_unitario >= 0),
  precio_unitario NUMERIC(12,2) NOT NULL CHECK (precio_unitario >= 0),
  importe         NUMERIC(12,2) GENERATED ALWAYS AS (cantidad * precio_unitario) STORED,
  UNIQUE (orden_id, refaccion_id)
);
CREATE INDEX IF NOT EXISTS ix_orden_refacciones_refaccion ON orden_refacciones (refaccion_id);

-- 6. COBRANZA: pagos
CREATE TABLE IF NOT EXISTS pagos (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio       VARCHAR(20) NOT NULL UNIQUE
              DEFAULT ('PG-' || TO_CHAR(NOW(), 'YYYY') || '-' ||
                       LPAD(NEXTVAL('seq_folio_pago')::TEXT, 5, '0')),
  orden_id    INTEGER       NOT NULL REFERENCES ordenes_trabajo(id),
  usuario_id  INTEGER       NOT NULL REFERENCES usuarios(id),
  monto       NUMERIC(12,2) NOT NULL CHECK (monto > 0),
  metodo      VARCHAR(15)   NOT NULL
              CHECK (metodo IN ('efectivo', 'debito', 'credito', 'transferencia')),
  tipo        VARCHAR(12)   NOT NULL
              CHECK (tipo IN ('anticipo', 'abono', 'liquidacion')),
  referencia  VARCHAR(60),
  estatus     VARCHAR(10)   NOT NULL DEFAULT 'aplicado'
              CHECK (estatus IN ('aplicado', 'anulado')),
  notas       TEXT,
  fecha_pago  TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_pagos_orden ON pagos (orden_id);
CREATE INDEX IF NOT EXISTS ix_pagos_fecha ON pagos (fecha_pago);

-- 7. TRAZABILIDAD: movimientos de inventario y auditoría
CREATE TABLE IF NOT EXISTS movimientos_inventario (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  refaccion_id   INTEGER      NOT NULL REFERENCES refacciones(id),
  orden_id       INTEGER      REFERENCES ordenes_trabajo(id),
  usuario_id     INTEGER      NOT NULL REFERENCES usuarios(id),
  tipo           VARCHAR(12)  NOT NULL
                 CHECK (tipo IN ('entrada', 'salida', 'ajuste', 'devolucion')),
  cantidad       INTEGER      NOT NULL CHECK (cantidad <> 0),
  stock_anterior INTEGER      NOT NULL CHECK (stock_anterior >= 0),
  stock_nuevo    INTEGER      NOT NULL CHECK (stock_nuevo >= 0),
  motivo         VARCHAR(200),
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_mov_refaccion ON movimientos_inventario (refaccion_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_mov_orden     ON movimientos_inventario (orden_id);

CREATE TABLE IF NOT EXISTS auditoria (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id        INTEGER      REFERENCES usuarios(id),
  accion            VARCHAR(30)  NOT NULL,
  entidad           VARCHAR(40)  NOT NULL,
  entidad_id        INTEGER,
  datos_anteriores  JSONB,
  datos_nuevos      JSONB,
  ip                VARCHAR(45),
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_auditoria_entidad ON auditoria (entidad, entidad_id);
CREATE INDEX IF NOT EXISTS ix_auditoria_usuario ON auditoria (usuario_id);
CREATE INDEX IF NOT EXISTS ix_auditoria_fecha   ON auditoria (created_at DESC);

-- 8. TRIGGERS de updated_at
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['usuarios', 'clientes', 'vehiculos', 'mecanicos',
                           'servicios', 'refacciones', 'ordenes_trabajo']
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%s_updated ON %I;', t, t);
    EXECUTE format(
      'CREATE TRIGGER trg_%s_updated BEFORE UPDATE ON %I
         FOR EACH ROW EXECUTE FUNCTION set_updated_at()', t, t);
  END LOOP;
END $$;

-- 9. VISTAS
CREATE OR REPLACE VIEW vw_ordenes_saldo AS
SELECT o.id AS orden_id,
       o.folio,
       o.estado,
       o.total,
       COALESCE(SUM(p.monto) FILTER (WHERE p.estatus = 'aplicado'), 0)            AS pagado,
       o.total - COALESCE(SUM(p.monto) FILTER (WHERE p.estatus = 'aplicado'), 0)  AS saldo
FROM ordenes_trabajo o
LEFT JOIN pagos p ON p.orden_id = o.id
GROUP BY o.id;

CREATE OR REPLACE VIEW vw_stock_bajo AS
SELECT r.id, r.sku, r.nombre, r.stock, r.stock_minimo,
       (r.stock_minimo - r.stock) AS faltante
FROM refacciones r
WHERE r.activo AND r.stock <= r.stock_minimo;
